apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-config
  namespace: iot-monitoring
data:
  KAFKA_BROKER: "kafka-service:9092"
  TOPIC_NAME: "sensor-data"
  RPC_PORT: "5000"
  RPC_HOST: "0.0.0.0"
  AGGREGATOR_PORT: "3000"
  SENSOR_NODE_RPC: "http://sensor-node-service:5000"
  VITE_API_URL: "http://aggregator-service:3000"
